[package]
name = "contract_canister_api"
version = "0.0.1"
edition = "2021"

[dependencies]
common_canister_types = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }
ic-cdk = { workspace = true }
